---
- name: Create users and groups
  block:
    - name: Create {{ create_group }} group
      group:
        name: "{{ create_group }}"
        state: present
    - name: Create {{ create_user }} user
      user:
        name: "{{ create_user }}"
        shell: /bin/bash
        groups: "{{ create_group }}"
    - name: Deploy SSH Key to {{ create_user }} user
      authorized_key: user={{ create_user }}
        key="{{ lookup('file', '{{ ssh_key_location }}') }}"
        state=present
